#!/usr/bin/bash

# fire os rev build script 
# BY 00ANDROID2468
# place your system.img at the root of this dir

sudo -v
# Keep-alive: update existing sudo time stamp if set, otherwise do nothing.
while true; do sudo -n true; sleep 60; kill -0 "$$" || exit; done 2>/dev/null &


echo "2BA Revamped build script"
echo "BY ANDROID2468"
echo ""

build="${1}"

# get the date 
fireDate="$(date +%b\ %d\ %Y)"
fileDate="$(date +%F)"

# Deleting out if exitis
if [ -d out ];
then
    rm -rf out
fi
mkdir out

# Checking if the system.img is in the root dir
if [ ! -f system.img ];
then
    echo " system.img is not in the root dir!"
    echo "leaving..."
    exit 
fi

# Copy system.img to out
echo "copying system.img to out"
cp -r system.img out/system.img

# Mounting system
echo "Mounting system.img to mount/"
sudo mount -t ext4 -o loop out/system.img mount/

# Checking if the system.img is mounted correctly
if [ ! -f mount/build.prop ]; then
    echo "Failed to mount correctly!"
    echo "leaving..."
    exit 
fi

echo "deleting apks"
sudo rm -rf -v mount/priv-app/VerizonIgnite
sudo rm -rf -v mount/priv-app/AmazonMobile
sudo rm -rf -v mount/priv-app/AmazonKindle
sudo rm -rf -v mount/app/BookmarkProvider
sudo rm -rf -v mount/priv-app/VZCloud
sudo rm -rf -v mount/priv-app/LGEasyHome
sudo rm -rf -v mount/priv-app/LGFileManager
sudo rm -rf -v mount/app/AmazonIMDb
sudo rm -rf -v mount/app/LGEIME
sudo rm -rf -v mount/app/LGEIME_THEME_BLACK3
sudo rm -rf -v mount/priv-app/LGVoiceCommandService
sudo rm -rf -v mount/priv-app/LGMapUI
sudo rm -rf -v mount/priv-app/Maluuba_QVoice
sudo rm -rf -v mount/app/LGWernickeManager
sudo rm -rf -v mount/priv-app/VZMessages
sudo rm -rf -v mount/priv-app/LGMusicWidget
sudo rm -rf -v mount/priv-app/LGMusic
sudo rm -rf -v mount/priv-app/MyInfozone
sudo rm -rf -v mount/priv-app/com.gotv.nflgamecenter.us.lite
sudo rm -rf -v mount/priv-app/SlackerRadio
sudo rm -rf -v mount/priv-app/LGSnapPage
sudo rm -rf -v mount/priv-app/VZMobileSecurity

sudo rm -rf -v mount/priv-app/LGThinkFreeViewer
sudo rm -rf -v mount/priv-app/LocationAgent
sudo rm -rf -v mount/priv-app/com.customermobile.preload.vzw
sudo rm -rf -v mount/priv-app/VZNavigator
sudo rm -rf -v mount/app/LGHome_Theme_Optimus/
sudo rm -rf -v mount/priv-app/HomeSelector
sudo rm -rf -v mount/priv-app/LGBackup
sudo rm -rf -v mount/priv-app/LGHome
sudo rm -rf -v mount/priv-app/LGUSMms

# gapps remover 
sudo rm -rf -v mount/addon.d/70-gapps.sh
sudo rm -rf -v mount/addon.d/71-faceunlock.sh
sudo rm -rf -v mount/addon.d/71-gapps-faceunlock.sh
sudo rm -rf -v mount/addon.d/74-googlecamera.sh
sudo rm -rf -v mount/addon.d/74-googlegallery.sh
sudo rm -rf -v mount/addon.d/75-googlegallery.sh
sudo rm -rf -v mount/addon.d/78-chromebrowser.sh
sudo rm -rf -v mount/app/AmbientSensePrebuilt
sudo rm -rf -v mount/app/AmbientSensePrebuilt.apk
sudo rm -rf -v mount/app/AmbientSensePrebuilt.odex
sudo rm -rf -v mount/app/AndroidForWork
sudo rm -rf -v mount/app/AndroidForWork.apk
sudo rm -rf -v mount/app/AndroidForWork.odex
sudo rm -rf -v mount/app/AndroidMigratePrebuilt
sudo rm -rf -v mount/app/AndroidMigratePrebuilt.apk
sudo rm -rf -v mount/app/AndroidMigratePrebuilt.odex
sudo rm -rf -v mount/app/AndroidPlatformServices
sudo rm -rf -v mount/app/AndroidPlatformServices.apk
sudo rm -rf -v mount/app/AndroidPlatformServices.odex
sudo rm -rf -v mount/app/BackupRestoreConfirmation
sudo rm -rf -v mount/app/BackupRestoreConfirmation.apk
sudo rm -rf -v mount/app/BackupRestoreConfirmation.odex
sudo rm -rf -v mount/app/Books
sudo rm -rf -v mount/app/Books.apk
sudo rm -rf -v mount/app/Books.odex
sudo rm -rf -v mount/app/BooksPhone
sudo rm -rf -v mount/app/BooksPhone.apk
sudo rm -rf -v mount/app/BooksPhone.odex
sudo rm -rf -v mount/app/BooksStub
sudo rm -rf -v mount/app/BooksStub.apk
sudo rm -rf -v mount/app/BooksStub.odex
sudo rm -rf -v mount/app/BrowserProviderProxy
sudo rm -rf -v mount/app/BrowserProviderProxy.apk
sudo rm -rf -v mount/app/BrowserProviderProxy.odex
sudo rm -rf -v mount/app/CalculatorGoogle
sudo rm -rf -v mount/app/CalculatorGoogle.apk
sudo rm -rf -v mount/app/CalculatorGoogle.odex
sudo rm -rf -v mount/app/CalculatorGooglePrebuilt
sudo rm -rf -v mount/app/CalculatorGooglePrebuilt.apk
sudo rm -rf -v mount/app/CalculatorGooglePrebuilt.odex
sudo rm -rf -v mount/app/Calendar
sudo rm -rf -v mount/app/Calendar.apk
sudo rm -rf -v mount/app/Calendar.odex
sudo rm -rf -v mount/app/CalendarGoogle
sudo rm -rf -v mount/app/CalendarGoogle.apk
sudo rm -rf -v mount/app/CalendarGoogle.odex
sudo rm -rf -v mount/app/CalendarGooglePrebuilt
sudo rm -rf -v mount/app/CalendarGooglePrebuilt.apk
sudo rm -rf -v mount/app/CalendarGooglePrebuilt.odex
sudo rm -rf -v mount/app/CalendarProvider
sudo rm -rf -v mount/app/CalendarProvider.apk
sudo rm -rf -v mount/app/CalendarProvider.odex
sudo rm -rf -v mount/app/CarHomeGoogle
sudo rm -rf -v mount/app/CarHomeGoogle.apk
sudo rm -rf -v mount/app/CarHomeGoogle.odex
sudo rm -rf -v mount/app/CellBroadcastReceiver
sudo rm -rf -v mount/app/CellBroadcastReceiver.apk
sudo rm -rf -v mount/app/CellBroadcastReceiver.odex
sudo rm -rf -v mount/app/Chrome
sudo rm -rf -v mount/app/Chrome.apk
sudo rm -rf -v mount/app/Chrome.odex
sudo rm -rf -v mount/app/ChromeBookmarksSyncAdapter
sudo rm -rf -v mount/app/ChromeBookmarksSyncAdapter.apk
sudo rm -rf -v mount/app/ChromeBookmarksSyncAdapter.odex
sudo rm -rf -v mount/app/CloudPrint
sudo rm -rf -v mount/app/CloudPrint.apk
sudo rm -rf -v mount/app/CloudPrint.odex
sudo rm -rf -v mount/app/CloudPrint2
sudo rm -rf -v mount/app/CloudPrint2.apk
sudo rm -rf -v mount/app/CloudPrint2.odex
sudo rm -rf -v mount/app/ConfigUpdater
sudo rm -rf -v mount/app/ConfigUpdater.apk
sudo rm -rf -v mount/app/ConfigUpdater.odex
sudo rm -rf -v mount/app/ConnMO
sudo rm -rf -v mount/app/ConnMO.apk
sudo rm -rf -v mount/app/ConnMO.odex
sudo rm -rf -v mount/app/Currents
sudo rm -rf -v mount/app/Currents.apk
sudo rm -rf -v mount/app/Currents.odex
sudo rm -rf -v mount/app/DeskClockGoogle
sudo rm -rf -v mount/app/DeskClockGoogle.apk
sudo rm -rf -v mount/app/DeskClockGoogle.odex
sudo rm -rf -v mount/app/DMAgent
sudo rm -rf -v mount/app/DMAgent.apk
sudo rm -rf -v mount/app/DMAgent.odex
sudo rm -rf -v mount/app/Drive
sudo rm -rf -v mount/app/Drive.apk
sudo rm -rf -v mount/app/Drive.odex
sudo rm -rf -v mount/app/Duo
sudo rm -rf -v mount/app/Duo.apk
sudo rm -rf -v mount/app/Duo.odex
sudo rm -rf -v mount/app/EditorsDocs
sudo rm -rf -v mount/app/EditorsDocs.apk
sudo rm -rf -v mount/app/EditorsDocs.odex
sudo rm -rf -v mount/app/EditorsDocsStub
sudo rm -rf -v mount/app/EditorsDocsStub.apk
sudo rm -rf -v mount/app/EditorsDocsStub.odex
sudo rm -rf -v mount/app/EditorsSheets
sudo rm -rf -v mount/app/EditorsSheets.apk
sudo rm -rf -v mount/app/EditorsSheets.odex
sudo rm -rf -v mount/app/EditorsSheetsStub
sudo rm -rf -v mount/app/EditorsSheetsStub.apk
sudo rm -rf -v mount/app/EditorsSheetsStub.odex
sudo rm -rf -v mount/app/EditorsSlides
sudo rm -rf -v mount/app/EditorsSlides.apk
sudo rm -rf -v mount/app/EditorsSlides.odex
sudo rm -rf -v mount/app/EditorsSlidesStub
sudo rm -rf -v mount/app/EditorsSlidesStub.apk
sudo rm -rf -v mount/app/EditorsSlidesStub.odex
sudo rm -rf -v mount/app/EuiccGoogle
sudo rm -rf -v mount/app/EuiccGoogle.apk
sudo rm -rf -v mount/app/EuiccGoogle.odex
sudo rm -rf -v mount/app/ExchangeServices
sudo rm -rf -v mount/app/ExchangeServices.apk
sudo rm -rf -v mount/app/ExchangeServices.odex
sudo rm -rf -v mount/app/FaceLock
sudo rm -rf -v mount/app/FaceLock.apk
sudo rm -rf -v mount/app/FaceLock.odex
sudo rm -rf -v mount/app/Finsky
sudo rm -rf -v mount/app/Finsky.apk
sudo rm -rf -v mount/app/Finsky.odex
sudo rm -rf -v mount/app/FitnessPrebuilt
sudo rm -rf -v mount/app/FitnessPrebuilt.apk
sudo rm -rf -v mount/app/FitnessPrebuilt.odex
sudo rm -rf -v mount/app/FOTAKill
sudo rm -rf -v mount/app/FOTAKill.apk
sudo rm -rf -v mount/app/FOTAKill.odex
sudo rm -rf -v mount/app/GalleryGoogle
sudo rm -rf -v mount/app/GalleryGoogle.apk
sudo rm -rf -v mount/app/GalleryGoogle.odex
sudo rm -rf -v mount/app/GCS
sudo rm -rf -v mount/app/GCS.apk
sudo rm -rf -v mount/app/GCS.odex
sudo rm -rf -v mount/app/GenieWidget
sudo rm -rf -v mount/app/GenieWidget.apk
sudo rm -rf -v mount/app/GenieWidget.odex
sudo rm -rf -v mount/app/Gmail
sudo rm -rf -v mount/app/Gmail.apk
sudo rm -rf -v mount/app/Gmail.odex
sudo rm -rf -v mount/app/Gmail2
sudo rm -rf -v mount/app/Gmail2.apk
sudo rm -rf -v mount/app/Gmail2.odex
sudo rm -rf -v mount/app/GmsCore
sudo rm -rf -v mount/app/GmsCore.apk
sudo rm -rf -v mount/app/GmsCore.odex
sudo rm -rf -v mount/app/GmsCore_update
sudo rm -rf -v mount/app/GmsCore_update.apk
sudo rm -rf -v mount/app/GmsCore_update.odex
sudo rm -rf -v mount/app/GmsCoreSetupPrebuilt
sudo rm -rf -v mount/app/GmsCoreSetupPrebuilt.apk
sudo rm -rf -v mount/app/GmsCoreSetupPrebuilt.odex
sudo rm -rf -v mount/app/GoogleBackupTransport
sudo rm -rf -v mount/app/GoogleBackupTransport.apk
sudo rm -rf -v mount/app/GoogleBackupTransport.odex
sudo rm -rf -v mount/app/GoogleCalendar
sudo rm -rf -v mount/app/GoogleCalendar.apk
sudo rm -rf -v mount/app/GoogleCalendar.odex
sudo rm -rf -v mount/app/GoogleCalendarSyncAdapter
sudo rm -rf -v mount/app/GoogleCalendarSyncAdapter.apk
sudo rm -rf -v mount/app/GoogleCalendarSyncAdapter.odex
sudo rm -rf -v mount/app/GoogleCamera
sudo rm -rf -v mount/app/GoogleCamera.apk
sudo rm -rf -v mount/app/GoogleCamera.odex
sudo rm -rf -v mount/app/GoogleCameraLegacy
sudo rm -rf -v mount/app/GoogleCameraLegacy.apk
sudo rm -rf -v mount/app/GoogleCameraLegacy.odex
sudo rm -rf -v mount/app/GoogleCloudPrint
sudo rm -rf -v mount/app/GoogleCloudPrint.apk
sudo rm -rf -v mount/app/GoogleCloudPrint.odex
sudo rm -rf -v mount/app/GoogleContacts
sudo rm -rf -v mount/app/GoogleContacts.apk
sudo rm -rf -v mount/app/GoogleContacts.odex
sudo rm -rf -v mount/app/GoogleDialer
sudo rm -rf -v mount/app/GoogleDialer.apk
sudo rm -rf -v mount/app/GoogleDialer.odex
sudo rm -rf -v mount/app/GoogleEars
sudo rm -rf -v mount/app/GoogleEars.apk
sudo rm -rf -v mount/app/GoogleEars.odex
sudo rm -rf -v mount/app/GoogleEarth
sudo rm -rf -v mount/app/GoogleEarth.apk
sudo rm -rf -v mount/app/GoogleEarth.odex
sudo rm -rf -v mount/app/GoogleExtServices
sudo rm -rf -v mount/app/GoogleExtServices.apk
sudo rm -rf -v mount/app/GoogleExtServices.odex
sudo rm -rf -v mount/app/GoogleExtShared
sudo rm -rf -v mount/app/GoogleExtShared.apk
sudo rm -rf -v mount/app/GoogleExtShared.odex
sudo rm -rf -v mount/app/GoogleFeedback
sudo rm -rf -v mount/app/GoogleFeedback.apk
sudo rm -rf -v mount/app/GoogleFeedback.odex
sudo rm -rf -v mount/app/GoogleHangouts
sudo rm -rf -v mount/app/GoogleHangouts.apk
sudo rm -rf -v mount/app/GoogleHangouts.odex
sudo rm -rf -v mount/app/GoogleHindiIME
sudo rm -rf -v mount/app/GoogleHindiIME.apk
sudo rm -rf -v mount/app/GoogleHindiIME.odex
sudo rm -rf -v mount/app/GoogleHome
sudo rm -rf -v mount/app/GoogleHome.apk
sudo rm -rf -v mount/app/GoogleHome.odex
sudo rm -rf -v mount/app/GoogleJapaneseInput
sudo rm -rf -v mount/app/GoogleJapaneseInput.apk
sudo rm -rf -v mount/app/GoogleJapaneseInput.odex
sudo rm -rf -v mount/app/GoogleKeep
sudo rm -rf -v mount/app/GoogleKeep.apk
sudo rm -rf -v mount/app/GoogleKeep.odex
sudo rm -rf -v mount/app/GoogleLatinIme
sudo rm -rf -v mount/app/GoogleLatinIme.apk
sudo rm -rf -v mount/app/GoogleLatinIme.odex
sudo rm -rf -v mount/app/GoogleLoginService
sudo rm -rf -v mount/app/GoogleLoginService.apk
sudo rm -rf -v mount/app/GoogleLoginService.odex
sudo rm -rf -v mount/app/GoogleMusic
sudo rm -rf -v mount/app/GoogleMusic.apk
sudo rm -rf -v mount/app/GoogleMusic.odex
sudo rm -rf -v mount/app/GoogleNow
sudo rm -rf -v mount/app/GoogleNow.apk
sudo rm -rf -v mount/app/GoogleNow.odex
sudo rm -rf -v mount/app/GoogleNowVoiceSearch
sudo rm -rf -v mount/app/GoogleNowVoiceSearch.apk
sudo rm -rf -v mount/app/GoogleNowVoiceSearch.odex
sudo rm -rf -v mount/app/GoogleOneTimeInitializer
sudo rm -rf -v mount/app/GoogleOneTimeInitializer.apk
sudo rm -rf -v mount/app/GoogleOneTimeInitializer.odex
sudo rm -rf -v mount/app/GooglePartnerSetup
sudo rm -rf -v mount/app/GooglePartnerSetup.apk
sudo rm -rf -v mount/app/GooglePartnerSetup.odex
sudo rm -rf -v mount/app/GooglePinyinIME
sudo rm -rf -v mount/app/GooglePinyinIME.apk
sudo rm -rf -v mount/app/GooglePinyinIME.odex
sudo rm -rf -v mount/app/GooglePlay
sudo rm -rf -v mount/app/GooglePlay.apk
sudo rm -rf -v mount/app/GooglePlay.odex
sudo rm -rf -v mount/app/GooglePlus
sudo rm -rf -v mount/app/GooglePlus.apk
sudo rm -rf -v mount/app/GooglePlus.odex
sudo rm -rf -v mount/app/GooglePrintRecommendationService
sudo rm -rf -v mount/app/GooglePrintRecommendationService.apk
sudo rm -rf -v mount/app/GooglePrintRecommendationService.odex
sudo rm -rf -v mount/app/GoogleQuickSearchBox
sudo rm -rf -v mount/app/GoogleQuickSearchBox.apk
sudo rm -rf -v mount/app/GoogleQuickSearchBox.odex
sudo rm -rf -v mount/app/GoogleSearch
sudo rm -rf -v mount/app/GoogleSearch.apk
sudo rm -rf -v mount/app/GoogleSearch.odex
sudo rm -rf -v mount/app/GoogleServicesFramework
sudo rm -rf -v mount/app/GoogleServicesFramework.apk
sudo rm -rf -v mount/app/GoogleServicesFramework.odex
sudo rm -rf -v mount/app/GoogleTTS
sudo rm -rf -v mount/app/GoogleTTS.apk
sudo rm -rf -v mount/app/GoogleTTS.odex
sudo rm -rf -v mount/app/GoogleVrCore
sudo rm -rf -v mount/app/GoogleVrCore.apk
sudo rm -rf -v mount/app/GoogleVrCore.odex
sudo rm -rf -v mount/app/GoogleZhuyinIME
sudo rm -rf -v mount/app/GoogleZhuyinIME.apk
sudo rm -rf -v mount/app/GoogleZhuyinIME.odex
sudo rm -rf -v mount/app/Hangouts
sudo rm -rf -v mount/app/Hangouts.apk
sudo rm -rf -v mount/app/Hangouts.odex
sudo rm -rf -v mount/app/HangoutsDialer
sudo rm -rf -v mount/app/HangoutsDialer.apk
sudo rm -rf -v mount/app/HangoutsDialer.odex
sudo rm -rf -v mount/app/HelpRtcPrebuilt
sudo rm -rf -v mount/app/HelpRtcPrebuilt.apk
sudo rm -rf -v mount/app/HelpRtcPrebuilt.odex
sudo rm -rf -v mount/app/HotwordEnrollment
sudo rm -rf -v mount/app/HotwordEnrollment.apk
sudo rm -rf -v mount/app/HotwordEnrollment.odex
sudo rm -rf -v mount/app/HotwordEnrollmentOKGoogleWCD9340
sudo rm -rf -v mount/app/HotwordEnrollmentOKGoogleWCD9340.apk
sudo rm -rf -v mount/app/HotwordEnrollmentOKGoogleWCD9340.odex
sudo rm -rf -v mount/app/HotwordEnrollmentXGoogleWCD9340
sudo rm -rf -v mount/app/HotwordEnrollmentXGoogleWCD9340.apk
sudo rm -rf -v mount/app/HotwordEnrollmentXGoogleWCD9340.odex
sudo rm -rf -v mount/app/iWnnIME
sudo rm -rf -v mount/app/iWnnIME.apk
sudo rm -rf -v mount/app/iWnnIME.odex
sudo rm -rf -v mount/app/iWnnIME_Kbd_White
sudo rm -rf -v mount/app/iWnnIME_Kbd_White.apk
sudo rm -rf -v mount/app/iWnnIME_Kbd_White.odex
sudo rm -rf -v mount/app/Keep
sudo rm -rf -v mount/app/Keep.apk
sudo rm -rf -v mount/app/Keep.odex
sudo rm -rf -v mount/app/KoreanIME
sudo rm -rf -v mount/app/KoreanIME.apk
sudo rm -rf -v mount/app/KoreanIME.odex
sudo rm -rf -v mount/app/LatinIME
sudo rm -rf -v mount/app/LatinIME.apk
sudo rm -rf -v mount/app/LatinIME.odex
sudo rm -rf -v mount/app/LatinImeDictionaryPack
sudo rm -rf -v mount/app/LatinImeDictionaryPack.apk
sudo rm -rf -v mount/app/LatinImeDictionaryPack.odex
sudo rm -rf -v mount/app/LatinImeGoogle
sudo rm -rf -v mount/app/LatinImeGoogle.apk
sudo rm -rf -v mount/app/LatinImeGoogle.odex
sudo rm -rf -v mount/app/LatinIMEGooglePrebuilt
sudo rm -rf -v mount/app/LatinIMEGooglePrebuilt.apk
sudo rm -rf -v mount/app/LatinIMEGooglePrebuilt.odex
sudo rm -rf -v mount/app/LatinImeTutorial
sudo rm -rf -v mount/app/LatinImeTutorial.apk
sudo rm -rf -v mount/app/LatinImeTutorial.odex
sudo rm -rf -v mount/app/Magazines
sudo rm -rf -v mount/app/Magazines.apk
sudo rm -rf -v mount/app/Magazines.odex
sudo rm -rf -v mount/app/Maps
sudo rm -rf -v mount/app/Maps.apk
sudo rm -rf -v mount/app/Maps.odex
sudo rm -rf -v mount/app/MarketUpdater
sudo rm -rf -v mount/app/MarketUpdater.apk
sudo rm -rf -v mount/app/MarketUpdater.odex
sudo rm -rf -v mount/app/MediaUploader
sudo rm -rf -v mount/app/MediaUploader.apk
sudo rm -rf -v mount/app/MediaUploader.odex
sudo rm -rf -v mount/app/Music2
sudo rm -rf -v mount/app/Music2.apk
sudo rm -rf -v mount/app/Music2.odex
sudo rm -rf -v mount/app/NetworkLocation
sudo rm -rf -v mount/app/NetworkLocation.apk
sudo rm -rf -v mount/app/NetworkLocation.odex
sudo rm -rf -v mount/app/Newsstand
sudo rm -rf -v mount/app/Newsstand.apk
sudo rm -rf -v mount/app/Newsstand.odex
sudo rm -rf -v mount/app/NewsstandStub
sudo rm -rf -v mount/app/NewsstandStub.apk
sudo rm -rf -v mount/app/NewsstandStub.odex
sudo rm -rf -v mount/app/NewsWeather
sudo rm -rf -v mount/app/NewsWeather.apk
sudo rm -rf -v mount/app/NewsWeather.odex
sudo rm -rf -v mount/app/NexusLauncherIcons
sudo rm -rf -v mount/app/NexusLauncherIcons.apk
sudo rm -rf -v mount/app/NexusLauncherIcons.odex
sudo rm -rf -v mount/app/NexusLauncherPrebuilt
sudo rm -rf -v mount/app/NexusLauncherPrebuilt.apk
sudo rm -rf -v mount/app/NexusLauncherPrebuilt.odex
sudo rm -rf -v mount/app/NexusWallpapersStubPrebuilt2017
sudo rm -rf -v mount/app/NexusWallpapersStubPrebuilt2017.apk
sudo rm -rf -v mount/app/NexusWallpapersStubPrebuilt2017.odex
sudo rm -rf -v mount/app/OccamQuickOffice
sudo rm -rf -v mount/app/OccamQuickOffice.apk
sudo rm -rf -v mount/app/OccamQuickOffice.odex
sudo rm -rf -v mount/app/OneTimeInitializer
sudo rm -rf -v mount/app/OneTimeInitializer.apk
sudo rm -rf -v mount/app/OneTimeInitializer.odex
sudo rm -rf -v mount/app/PartnerBookmarksProvider
sudo rm -rf -v mount/app/PartnerBookmarksProvider.apk
sudo rm -rf -v mount/app/PartnerBookmarksProvider.odex
sudo rm -rf -v mount/app/Phonesky
sudo rm -rf -v mount/app/Phonesky.apk
sudo rm -rf -v mount/app/Phonesky.odex
sudo rm -rf -v mount/app/Photos
sudo rm -rf -v mount/app/Photos.apk
sudo rm -rf -v mount/app/Photos.odex
sudo rm -rf -v mount/app/PlayAutoInstallConfig
sudo rm -rf -v mount/app/PlayAutoInstallConfig.apk
sudo rm -rf -v mount/app/PlayAutoInstallConfig.odex
sudo rm -rf -v mount/app/PlayGames
sudo rm -rf -v mount/app/PlayGames.apk
sudo rm -rf -v mount/app/PlayGames.odex
sudo rm -rf -v mount/app/PlayStore
sudo rm -rf -v mount/app/PlayStore.apk
sudo rm -rf -v mount/app/PlayStore.odex
sudo rm -rf -v mount/app/PlusOne
sudo rm -rf -v mount/app/PlusOne.apk
sudo rm -rf -v mount/app/PlusOne.odex
sudo rm -rf -v mount/app/PrebuiltBugle
sudo rm -rf -v mount/app/PrebuiltBugle.apk
sudo rm -rf -v mount/app/PrebuiltBugle.odex
sudo rm -rf -v mount/app/PrebuiltBugleStub
sudo rm -rf -v mount/app/PrebuiltBugleStub.apk
sudo rm -rf -v mount/app/PrebuiltBugleStub.odex
sudo rm -rf -v mount/app/PrebuiltDeskClockGoogle
sudo rm -rf -v mount/app/PrebuiltDeskClockGoogle.apk
sudo rm -rf -v mount/app/PrebuiltDeskClockGoogle.odex
sudo rm -rf -v mount/app/PrebuiltEmailGoogle
sudo rm -rf -v mount/app/PrebuiltEmailGoogle.apk
sudo rm -rf -v mount/app/PrebuiltEmailGoogle.odex
sudo rm -rf -v mount/app/PrebuiltExchange3Google
sudo rm -rf -v mount/app/PrebuiltExchange3Google.apk
sudo rm -rf -v mount/app/PrebuiltExchange3Google.odex
sudo rm -rf -v mount/app/PrebuiltGmail
sudo rm -rf -v mount/app/PrebuiltGmail.apk
sudo rm -rf -v mount/app/PrebuiltGmail.odex
sudo rm -rf -v mount/app/PrebuiltGmsCore
sudo rm -rf -v mount/app/PrebuiltGmsCore.apk
sudo rm -rf -v mount/app/PrebuiltGmsCore.odex
sudo rm -rf -v mount/app/PrebuiltGmsCorePix
sudo rm -rf -v mount/app/PrebuiltGmsCorePix.apk
sudo rm -rf -v mount/app/PrebuiltGmsCorePix.odex
sudo rm -rf -v mount/app/PrebuiltKeep
sudo rm -rf -v mount/app/PrebuiltKeep.apk
sudo rm -rf -v mount/app/PrebuiltKeep.odex
sudo rm -rf -v mount/app/PrebuiltKeepStub
sudo rm -rf -v mount/app/PrebuiltKeepStub.apk
sudo rm -rf -v mount/app/PrebuiltKeepStub.odex
sudo rm -rf -v mount/app/PrebuiltNewsWeather
sudo rm -rf -v mount/app/PrebuiltNewsWeather.apk
sudo rm -rf -v mount/app/PrebuiltNewsWeather.odex
sudo rm -rf -v mount/app/PrintSpooler
sudo rm -rf -v mount/app/PrintSpooler.apk
sudo rm -rf -v mount/app/PrintSpooler.odex
sudo rm -rf -v mount/app/QuickOffice
sudo rm -rf -v mount/app/QuickOffice.apk
sudo rm -rf -v mount/app/QuickOffice.odex
sudo rm -rf -v mount/app/QuickSearchBox
sudo rm -rf -v mount/app/QuickSearchBox.apk
sudo rm -rf -v mount/app/QuickSearchBox.odex
sudo rm -rf -v mount/app/SettingsGoogle
sudo rm -rf -v mount/app/SettingsGoogle.apk
sudo rm -rf -v mount/app/SettingsGoogle.odex
sudo rm -rf -v mount/app/SetupWizard
sudo rm -rf -v mount/app/SetupWizard.apk
sudo rm -rf -v mount/app/SetupWizard.odex
sudo rm -rf -v mount/app/StorageManagerGoogle
sudo rm -rf -v mount/app/StorageManagerGoogle.apk
sudo rm -rf -v mount/app/StorageManagerGoogle.odex
sudo rm -rf -v mount/app/Street
sudo rm -rf -v mount/app/Street.apk
sudo rm -rf -v mount/app/Street.odex
sudo rm -rf -v mount/app/SystemUIGoogle
sudo rm -rf -v mount/app/SystemUIGoogle.apk
sudo rm -rf -v mount/app/SystemUIGoogle.odex
sudo rm -rf -v mount/app/Tag.apk
sudo rm -rf -v mount/app/TagGoogle
sudo rm -rf -v mount/app/TagGoogle.apk
sudo rm -rf -v mount/app/TagGoogle.odex
sudo rm -rf -v mount/app/Talk
sudo rm -rf -v mount/app/Talk.apk
sudo rm -rf -v mount/app/Talk.odex
sudo rm -rf -v mount/app/talkback
sudo rm -rf -v mount/app/talkback.apk
sudo rm -rf -v mount/app/talkback.odex
sudo rm -rf -v mount/app/TranslatePrebuilt
sudo rm -rf -v mount/app/TranslatePrebuilt.apk
sudo rm -rf -v mount/app/TranslatePrebuilt.odex
sudo rm -rf -v mount/app/Turbo
sudo rm -rf -v mount/app/Turbo.apk
sudo rm -rf -v mount/app/Turbo.odex
sudo rm -rf -v mount/app/Tycho
sudo rm -rf -v mount/app/Tycho.apk
sudo rm -rf -v mount/app/Tycho.odex
sudo rm -rf -v mount/app/Velvet
sudo rm -rf -v mount/app/Velvet.apk
sudo rm -rf -v mount/app/Velvet.odex
sudo rm -rf -v mount/app/Velvet_update
sudo rm -rf -v mount/app/Velvet_update.apk
sudo rm -rf -v mount/app/Velvet_update.odex
sudo rm -rf -v mount/app/Vending
sudo rm -rf -v mount/app/Vending.apk
sudo rm -rf -v mount/app/Vending.odex
sudo rm -rf -v mount/app/Videos
sudo rm -rf -v mount/app/Videos.apk
sudo rm -rf -v mount/app/Videos.odex
sudo rm -rf -v mount/app/VoiceSearch
sudo rm -rf -v mount/app/VoiceSearch.apk
sudo rm -rf -v mount/app/VoiceSearch.odex
sudo rm -rf -v mount/app/VoiceSearchStub
sudo rm -rf -v mount/app/VoiceSearchStub.apk
sudo rm -rf -v mount/app/VoiceSearchStub.odex
sudo rm -rf -v mount/app/Wallet
sudo rm -rf -v mount/app/Wallet.apk
sudo rm -rf -v mount/app/Wallet.odex
sudo rm -rf -v mount/app/WallpaperPickerGooglePrebuilt
sudo rm -rf -v mount/app/WallpaperPickerGooglePrebuilt.apk
sudo rm -rf -v mount/app/WallpaperPickerGooglePrebuilt.odex
sudo rm -rf -v mount/app/WallpapersBReel2017
sudo rm -rf -v mount/app/WallpapersBReel2017.apk
sudo rm -rf -v mount/app/WallpapersBReel2017.odex
sudo rm -rf -v mount/app/YouTube
sudo rm -rf -v mount/app/YouTube.apk
sudo rm -rf -v mount/app/YouTube.odex
sudo rm -rf -v mount/bin/wmdsi
sudo rm -rf -v mount/etc/ambient/matcher.leveldb
sudo rm -rf -v mount/etc/default-permissions/default-permissions.xml
sudo rm -rf -v mount/etc/default-permissions/opengapps-permissions.xml
sudo rm -rf -v mount/etc/firmware/dnd.descriptor
sudo rm -rf -v mount/etc/firmware/dnd.sound_model
sudo rm -rf -v mount/etc/firmware/music_detector.descriptor
sudo rm -rf -v mount/etc/firmware/music_detector.sound_model
sudo rm -rf -v mount/etc/g.prop
sudo rm -rf -v mount/etc/permissions/com.google.android.camera.experimental2015.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.camera.experimental2016.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.camera.experimental2017.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.camera.experimental2018.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.camera2.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.dialer.support.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.maps.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.media.effects.xml
sudo rm -rf -v mount/etc/permissions/com.google.android.pano.v1.xml
sudo rm -rf -v mount/etc/permissions/com.google.vr.platform.xml
sudo rm -rf -v mount/etc/permissions/com.google.widevine.software.drm.xml
sudo rm -rf -v mount/etc/permissions/features.xml
sudo rm -rf -v mount/etc/preferred-apps/google.xml
sudo rm -rf -v mount/etc/sysconfig/dialer_experience.xml
sudo rm -rf -v mount/etc/sysconfig/framework-sysconfig.xml
sudo rm -rf -v mount/etc/sysconfig/google.xml
sudo rm -rf -v mount/etc/sysconfig/google_build.xml
sudo rm -rf -v mount/etc/sysconfig/google_vr_build.xml
sudo rm -rf -v mount/etc/sysconfig/pixel_2017.xml
sudo rm -rf -v mount/etc/sysconfig/pixel_2018.xml
sudo rm -rf -v mount/etc/sysconfig/whitelist_com.android.omadm.service.xml
sudo rm -rf -v mount/etc/updatecmds/google_generic_update.txt
sudo rm -rf -v mount/framework/com.google.android.camera.experimental2015.jar
sudo rm -rf -v mount/framework/com.google.android.camera.experimental2016.jar
sudo rm -rf -v mount/framework/com.google.android.camera2.jar
sudo rm -rf -v mount/framework/com.google.android.dialer.support.jar
sudo rm -rf -v mount/framework/com.google.android.maps.jar
sudo rm -rf -v mount/framework/com.google.android.media.effects.jar
sudo rm -rf -v mount/framework/com.google.android.pano.v1.jar
sudo rm -rf -v mount/framework/com.google.widevine.software.drm.jar
sudo rm -rf -v mount/lib/lib_dic_*
sudo rm -rf -v mount/lib/libAppDataSearch.so
sudo rm -rf -v mount/lib/libbitmap_parcel.so
sudo rm -rf -v mount/lib/libchrome*
sudo rm -rf -v mount/lib/libchromeview.so
sudo rm -rf -v mount/lib/libconscrypt_gmscore_jni.so
sudo rm -rf -v mount/lib/libcrashreporter.so
sudo rm -rf -v mount/lib/libdocscanner*
sudo rm -rf -v mount/lib/libdocsimageutils.so
sudo rm -rf -v mount/lib/libearthandroid.so
sudo rm -rf -v mount/lib/libearthmobile.so
sudo rm -rf -v mount/lib/libEnjemailuri.so
sudo rm -rf -v mount/lib/libennjcon.so
sudo rm -rf -v mount/lib/libennjubase*
sudo rm -rf -v mount/lib/libennjyomi.so
sudo rm -rf -v mount/lib/libfacelock_jni.so
sudo rm -rf -v mount/lib/libfacenet.so
sudo rm -rf -v mount/lib/libfacetracker.so
sudo rm -rf -v mount/lib/libfilterframework_jni.so
sudo rm -rf -v mount/lib/libfilterpack_facedetect.so
sudo rm -rf -v mount/lib/libflint_engine_jni_api.so
sudo rm -rf -v mount/lib/libfoxit.so
sudo rm -rf -v mount/lib/libframesequence.so
sudo rm -rf -v mount/lib/libfrsdk.so
sudo rm -rf -v mount/lib/libgames_rtmp_jni.so
sudo rm -rf -v mount/lib/libgcam.so
sudo rm -rf -v mount/lib/libgcam_swig_jni.so
sudo rm -rf -v mount/lib/libgcastv2*
sudo rm -rf -v mount/lib/libgcomm_jni.so
sudo rm -rf -v mount/lib/libgmm-jni.so
sudo rm -rf -v mount/lib/libgms-ocrclient.so
sudo rm -rf -v mount/lib/libgmscore.so
sudo rm -rf -v mount/lib/libgoggles_clientvision.so
sudo rm -rf -v mount/lib/libgoogle_*
sudo rm -rf -v mount/lib/libgtalk_jni.so
sudo rm -rf -v mount/lib/libgtalk_stabilize.so
sudo rm -rf -v mount/lib/libiwnn.so
sudo rm -rf -v mount/lib/libjgcastservice.so
sudo rm -rf -v mount/lib/libjni_eglfence.so
sudo rm -rf -v mount/lib/libjni_filtershow_filters.so
sudo rm -rf -v mount/lib/libjni_googlepinyinime_*
sudo rm -rf -v mount/lib/libjni_koreanime.so
sudo rm -rf -v mount/lib/libjni_t13n_shared_engine.so
sudo rm -rf -v mount/lib/libjni_tinyplanet.so
sudo rm -rf -v mount/lib/libjni_unbundled_latinimegoogle.so
sudo rm -rf -v mount/lib/liblightcycle.so
sudo rm -rf -v mount/lib/liblinearalloc.so
sudo rm -rf -v mount/lib/libm2ts_player.so
sudo rm -rf -v mount/lib/libmicro_hotword_jni.so
sudo rm -rf -v mount/lib/libmoviemaker-jni.so
sudo rm -rf -v mount/lib/libnativehelper_compat.so
sudo rm -rf -v mount/lib/libnativehelper_compat_libc++.so
sudo rm -rf -v mount/lib/libndk1.so
sudo rm -rf -v mount/lib/libnetjni.so
sudo rm -rf -v mount/lib/libnjaddress.so
sudo rm -rf -v mount/lib/libnjcon.so
sudo rm -rf -v mount/lib/libnjemoji.so
sudo rm -rf -v mount/lib/libnjexyomi.so
sudo rm -rf -v mount/lib/libnjfzk.so
sudo rm -rf -v mount/lib/libnjkaomoji.so
sudo rm -rf -v mount/lib/libnjname.so
sudo rm -rf -v mount/lib/libnjtan.so
sudo rm -rf -v mount/lib/libnjubase*
sudo rm -rf -v mount/lib/libnjubaseidx1.so
sudo rm -rf -v mount/lib/libnjubaseidx2.so
sudo rm -rf -v mount/lib/libocrclient.so
sudo rm -rf -v mount/lib/libpatts_engine_*
sudo rm -rf -v mount/lib/libphotoeditor_native.so
sudo rm -rf -v mount/lib/libpicowrapper.so
sudo rm -rf -v mount/lib/libplus_jni_v8.so
sudo rm -rf -v mount/lib/librectifier*
sudo rm -rf -v mount/lib/librefocus.so
sudo rm -rf -v mount/lib/librs.antblur.so
sudo rm -rf -v mount/lib/librs.antblur_*
sudo rm -rf -v mount/lib/librs.drama.so
sudo rm -rf -v mount/lib/librs.film_base.so
sudo rm -rf -v mount/lib/librs.fixedframe.so
sudo rm -rf -v mount/lib/librs.grey.so
sudo rm -rf -v mount/lib/librs.image_wrapper.so
sudo rm -rf -v mount/lib/librs.layered_filter_f32.so
sudo rm -rf -v mount/lib/librs.retrolux.so
sudo rm -rf -v mount/lib/librsjni.so
sudo rm -rf -v mount/lib/libRSSupport.so
sudo rm -rf -v mount/lib/libsense.so
sudo rm -rf -v mount/lib/libspeexwrapper.so
sudo rm -rf -v mount/lib/libspeexwrapper_ub*
sudo rm -rf -v mount/lib/libsslwrapper_jni.so
sudo rm -rf -v mount/lib/libstlport_shared.so
sudo rm -rf -v mount/lib/libvcdecoder_jni.so
sudo rm -rf -v mount/lib/libvideochat_jni.so
sudo rm -rf -v mount/lib/libvideochat_stabilize.so
sudo rm -rf -v mount/lib/libvoicesearch.so
sudo rm -rf -v mount/lib/libvorbisencoder.so
sudo rm -rf -v mount/lib/libwallpapers-breel-jni.so
sudo rm -rf -v mount/lib/libwebp_android.so
sudo rm -rf -v mount/lib/libwebrtc_audio_coding.so
sudo rm -rf -v mount/lib/libWhisper.so
sudo rm -rf -v mount/lib/libWVphoneAPI.so
sudo rm -rf -v mount/lib/modules/modules.dep.bb
sudo rm -rf -v mount/lib64/lib_dic_*
sudo rm -rf -v mount/lib64/libAppDataSearch.so
sudo rm -rf -v mount/lib64/libbitmap_parcel.so
sudo rm -rf -v mount/lib64/libchrome*
sudo rm -rf -v mount/lib64/libchromeview.so
sudo rm -rf -v mount/lib64/libconscrypt_gmscore_jni.so
sudo rm -rf -v mount/lib64/libcrashreporter.so
sudo rm -rf -v mount/lib64/libdocscanner*
sudo rm -rf -v mount/lib64/libdocsimageutils.so
sudo rm -rf -v mount/lib64/libearthandroid.so
sudo rm -rf -v mount/lib64/libearthmobile.so
sudo rm -rf -v mount/lib64/libEnjemailuri.so
sudo rm -rf -v mount/lib64/libennjcon.so
sudo rm -rf -v mount/lib64/libennjubase*
sudo rm -rf -v mount/lib64/libennjyomi.so
sudo rm -rf -v mount/lib64/libfacelock_jni.so
sudo rm -rf -v mount/lib64/libfacenet.so
sudo rm -rf -v mount/lib64/libfacetracker.so
sudo rm -rf -v mount/lib64/libfilterframework_jni.so
sudo rm -rf -v mount/lib64/libfilterpack_facedetect.so
sudo rm -rf -v mount/lib64/libflint_engine_jni_api.so
sudo rm -rf -v mount/lib64/libfoxit.so
sudo rm -rf -v mount/lib64/libframesequence.so
sudo rm -rf -v mount/lib64/libfrsdk.so
sudo rm -rf -v mount/lib64/libgames_rtmp_jni.so
sudo rm -rf -v mount/lib64/libgcam.so
sudo rm -rf -v mount/lib64/libgcam_swig_jni.so
sudo rm -rf -v mount/lib64/libgcastv2*
sudo rm -rf -v mount/lib64/libgcomm_jni.so
sudo rm -rf -v mount/lib64/libgmm-jni.so
sudo rm -rf -v mount/lib64/libgms-ocrclient.so
sudo rm -rf -v mount/lib64/libgmscore.so
sudo rm -rf -v mount/lib64/libgoggles_clientvision.so
sudo rm -rf -v mount/lib64/libgoogle_*
sudo rm -rf -v mount/lib64/libgtalk_jni.so
sudo rm -rf -v mount/lib64/libgtalk_stabilize.so
sudo rm -rf -v mount/lib64/libiwnn.so
sudo rm -rf -v mount/lib64/libjgcastservice.so
sudo rm -rf -v mount/lib64/libjni_eglfence.so
sudo rm -rf -v mount/lib64/libjni_filtershow_filters.so
sudo rm -rf -v mount/lib64/libjni_googlepinyinime_*
sudo rm -rf -v mount/lib64/libjni_koreanime.so
sudo rm -rf -v mount/lib64/libjni_latinime.so
sudo rm -rf -v mount/lib64/libjni_latinimegoogle.so
sudo rm -rf -v mount/lib64/libjni_t13n_shared_engine.so
sudo rm -rf -v mount/lib64/libjni_tinyplanet.so
sudo rm -rf -v mount/lib64/libjni_unbundled_latinimegoogle.so
sudo rm -rf -v mount/lib64/liblightcycle.so
sudo rm -rf -v mount/lib64/liblinearalloc.so
sudo rm -rf -v mount/lib64/libm2ts_player.so
sudo rm -rf -v mount/lib64/libmicro_hotword_jni.so
sudo rm -rf -v mount/lib64/libmoviemaker-jni.so
sudo rm -rf -v mount/lib64/libnativehelper_compat.so
sudo rm -rf -v mount/lib64/libnativehelper_compat_libc++.so
sudo rm -rf -v mount/lib64/libndk1.so
sudo rm -rf -v mount/lib64/libnetjni.so
sudo rm -rf -v mount/lib64/libnjaddress.so
sudo rm -rf -v mount/lib64/libnjcon.so
sudo rm -rf -v mount/lib64/libnjemoji.so
sudo rm -rf -v mount/lib64/libnjexyomi.so
sudo rm -rf -v mount/lib64/libnjfzk.so
sudo rm -rf -v mount/lib64/libnjkaomoji.so
sudo rm -rf -v mount/lib64/libnjname.so
sudo rm -rf -v mount/lib64/libnjtan.so
sudo rm -rf -v mount/lib64/libnjubase*
sudo rm -rf -v mount/lib64/libnjubaseidx1.so
sudo rm -rf -v mount/lib64/libnjubaseidx2.so
sudo rm -rf -v mount/lib64/libocrclient.so
sudo rm -rf -v mount/lib64/libpatts_engine_*
sudo rm -rf -v mount/lib64/libphotoeditor_native.so
sudo rm -rf -v mount/lib64/libpicowrapper.so
sudo rm -rf -v mount/lib64/libplus_jni_v8.so
sudo rm -rf -v mount/lib64/librectifier*
sudo rm -rf -v mount/lib64/librefocus.so
sudo rm -rf -v mount/lib64/librs.antblur.so
sudo rm -rf -v mount/lib64/librs.antblur_*
sudo rm -rf -v mount/lib64/librs.drama.so
sudo rm -rf -v mount/lib64/librs.film_base.so
sudo rm -rf -v mount/lib64/librs.fixedframe.so
sudo rm -rf -v mount/lib64/librs.grey.so
sudo rm -rf -v mount/lib64/librs.image_wrapper.so
sudo rm -rf -v mount/lib64/librs.layered_filter_f32.so
sudo rm -rf -v mount/lib64/librs.retrolux.so
sudo rm -rf -v mount/lib64/librsjni.so
sudo rm -rf -v mount/lib64/libRSSupport.so
sudo rm -rf -v mount/lib64/libsense.so
sudo rm -rf -v mount/lib64/libspeexwrapper.so
sudo rm -rf -v mount/lib64/libspeexwrapper_ub*
sudo rm -rf -v mount/lib64/libsslwrapper_jni.so
sudo rm -rf -v mount/lib64/libstlport_shared.so
sudo rm -rf -v mount/lib64/libvcdecoder_jni.so
sudo rm -rf -v mount/lib64/libvideochat_jni.so
sudo rm -rf -v mount/lib64/libvideochat_stabilize.so
sudo rm -rf -v mount/lib64/libvoicesearch.so
sudo rm -rf -v mount/lib64/libvorbisencoder.so
sudo rm -rf -v mount/lib64/libwallpapers-breel-jni.so
sudo rm -rf -v mount/lib64/libwebp_android.so
sudo rm -rf -v mount/lib64/libwebrtc_audio_coding.so
sudo rm -rf -v mount/lib64/libWhisper.so
sudo rm -rf -v mount/lib64/libWVphoneAPI.so
sudo rm -rf -v mount/lib64/modules/modules.dep.bb
sudo rm -rf -v mount/priv-app/AmbientSensePrebuilt
sudo rm -rf -v mount/priv-app/AmbientSensePrebuilt.apk
sudo rm -rf -v mount/priv-app/AmbientSensePrebuilt.odex
sudo rm -rf -v mount/priv-app/AndroidForWork
sudo rm -rf -v mount/priv-app/AndroidForWork.apk
sudo rm -rf -v mount/priv-app/AndroidForWork.odex
sudo rm -rf -v mount/priv-app/AndroidMigratePrebuilt
sudo rm -rf -v mount/priv-app/AndroidMigratePrebuilt.apk
sudo rm -rf -v mount/priv-app/AndroidMigratePrebuilt.odex
sudo rm -rf -v mount/priv-app/AndroidPlatformServices
sudo rm -rf -v mount/priv-app/AndroidPlatformServices.apk
sudo rm -rf -v mount/priv-app/AndroidPlatformServices.odex
sudo rm -rf -v mount/priv-app/BackupRestoreConfirmation
sudo rm -rf -v mount/priv-app/BackupRestoreConfirmation.apk
sudo rm -rf -v mount/priv-app/BackupRestoreConfirmation.odex
sudo rm -rf -v mount/priv-app/Books
sudo rm -rf -v mount/priv-app/Books.apk
sudo rm -rf -v mount/priv-app/Books.odex
sudo rm -rf -v mount/priv-app/BooksPhone
sudo rm -rf -v mount/priv-app/BooksPhone.apk
sudo rm -rf -v mount/priv-app/BooksPhone.odex
sudo rm -rf -v mount/priv-app/BooksStub
sudo rm -rf -v mount/priv-app/BooksStub.apk
sudo rm -rf -v mount/priv-app/BooksStub.odex
sudo rm -rf -v mount/priv-app/BrowserProviderProxy
sudo rm -rf -v mount/priv-app/BrowserProviderProxy.apk
sudo rm -rf -v mount/priv-app/BrowserProviderProxy.odex
sudo rm -rf -v mount/priv-app/CalculatorGoogle
sudo rm -rf -v mount/priv-app/CalculatorGoogle.apk
sudo rm -rf -v mount/priv-app/CalculatorGoogle.odex
sudo rm -rf -v mount/priv-app/CalculatorGooglePrebuilt
sudo rm -rf -v mount/priv-app/CalculatorGooglePrebuilt.apk
sudo rm -rf -v mount/priv-app/CalculatorGooglePrebuilt.odex
sudo rm -rf -v mount/priv-app/Calendar
sudo rm -rf -v mount/priv-app/Calendar.apk
sudo rm -rf -v mount/priv-app/Calendar.odex
sudo rm -rf -v mount/priv-app/CalendarGoogle
sudo rm -rf -v mount/priv-app/CalendarGoogle.apk
sudo rm -rf -v mount/priv-app/CalendarGoogle.odex
sudo rm -rf -v mount/priv-app/CalendarGooglePrebuilt
sudo rm -rf -v mount/priv-app/CalendarGooglePrebuilt.apk
sudo rm -rf -v mount/priv-app/CalendarGooglePrebuilt.odex
sudo rm -rf -v mount/priv-app/CalendarProvider
sudo rm -rf -v mount/priv-app/CalendarProvider.apk
sudo rm -rf -v mount/priv-app/CalendarProvider.odex
sudo rm -rf -v mount/priv-app/CarHomeGoogle
sudo rm -rf -v mount/priv-app/CarHomeGoogle.apk
sudo rm -rf -v mount/priv-app/CarHomeGoogle.odex
sudo rm -rf -v mount/priv-app/CellBroadcastReceiver
sudo rm -rf -v mount/priv-app/CellBroadcastReceiver.apk
sudo rm -rf -v mount/priv-app/CellBroadcastReceiver.odex
sudo rm -rf -v mount/priv-app/Chrome
sudo rm -rf -v mount/priv-app/Chrome.apk
sudo rm -rf -v mount/priv-app/Chrome.odex
sudo rm -rf -v mount/priv-app/ChromeBookmarksSyncAdapter
sudo rm -rf -v mount/priv-app/ChromeBookmarksSyncAdapter.apk
sudo rm -rf -v mount/priv-app/ChromeBookmarksSyncAdapter.odex
sudo rm -rf -v mount/priv-app/CloudPrint
sudo rm -rf -v mount/priv-app/CloudPrint.apk
sudo rm -rf -v mount/priv-app/CloudPrint.odex
sudo rm -rf -v mount/priv-app/CloudPrint2
sudo rm -rf -v mount/priv-app/CloudPrint2.apk
sudo rm -rf -v mount/priv-app/CloudPrint2.odex
sudo rm -rf -v mount/priv-app/ConfigUpdater
sudo rm -rf -v mount/priv-app/ConfigUpdater.apk
sudo rm -rf -v mount/priv-app/ConfigUpdater.odex
sudo rm -rf -v mount/priv-app/ConnMO
sudo rm -rf -v mount/priv-app/ConnMO.apk
sudo rm -rf -v mount/priv-app/ConnMO.odex
sudo rm -rf -v mount/priv-app/Currents
sudo rm -rf -v mount/priv-app/Currents.apk
sudo rm -rf -v mount/priv-app/Currents.odex
sudo rm -rf -v mount/priv-app/DeskClockGoogle
sudo rm -rf -v mount/priv-app/DeskClockGoogle.apk
sudo rm -rf -v mount/priv-app/DeskClockGoogle.odex
sudo rm -rf -v mount/priv-app/DMAgent
sudo rm -rf -v mount/priv-app/DMAgent.apk
sudo rm -rf -v mount/priv-app/DMAgent.odex
sudo rm -rf -v mount/priv-app/Drive
sudo rm -rf -v mount/priv-app/Drive.apk
sudo rm -rf -v mount/priv-app/Drive.odex
sudo rm -rf -v mount/priv-app/Duo
sudo rm -rf -v mount/priv-app/Duo.apk
sudo rm -rf -v mount/priv-app/Duo.odex
sudo rm -rf -v mount/priv-app/EditorsDocs
sudo rm -rf -v mount/priv-app/EditorsDocs.apk
sudo rm -rf -v mount/priv-app/EditorsDocs.odex
sudo rm -rf -v mount/priv-app/EditorsDocsStub
sudo rm -rf -v mount/priv-app/EditorsDocsStub.apk
sudo rm -rf -v mount/priv-app/EditorsDocsStub.odex
sudo rm -rf -v mount/priv-app/EditorsSheets
sudo rm -rf -v mount/priv-app/EditorsSheets.apk
sudo rm -rf -v mount/priv-app/EditorsSheets.odex
sudo rm -rf -v mount/priv-app/EditorsSheetsStub
sudo rm -rf -v mount/priv-app/EditorsSheetsStub.apk
sudo rm -rf -v mount/priv-app/EditorsSheetsStub.odex
sudo rm -rf -v mount/priv-app/EditorsSlides
sudo rm -rf -v mount/priv-app/EditorsSlides.apk
sudo rm -rf -v mount/priv-app/EditorsSlides.odex
sudo rm -rf -v mount/priv-app/EditorsSlidesStub
sudo rm -rf -v mount/priv-app/EditorsSlidesStub.apk
sudo rm -rf -v mount/priv-app/EditorsSlidesStub.odex
sudo rm -rf -v mount/priv-app/EuiccGoogle
sudo rm -rf -v mount/priv-app/EuiccGoogle.apk
sudo rm -rf -v mount/priv-app/EuiccGoogle.odex
sudo rm -rf -v mount/priv-app/ExchangeServices
sudo rm -rf -v mount/priv-app/ExchangeServices.apk
sudo rm -rf -v mount/priv-app/ExchangeServices.odex
sudo rm -rf -v mount/priv-app/FaceLock
sudo rm -rf -v mount/priv-app/FaceLock.apk
sudo rm -rf -v mount/priv-app/FaceLock.odex
sudo rm -rf -v mount/priv-app/Finsky
sudo rm -rf -v mount/priv-app/Finsky.apk
sudo rm -rf -v mount/priv-app/Finsky.odex
sudo rm -rf -v mount/priv-app/FitnessPrebuilt
sudo rm -rf -v mount/priv-app/FitnessPrebuilt.apk
sudo rm -rf -v mount/priv-app/FitnessPrebuilt.odex
sudo rm -rf -v mount/priv-app/FOTAKill
sudo rm -rf -v mount/priv-app/FOTAKill.apk
sudo rm -rf -v mount/priv-app/FOTAKill.odex
sudo rm -rf -v mount/priv-app/GalleryGoogle
sudo rm -rf -v mount/priv-app/GalleryGoogle.apk
sudo rm -rf -v mount/priv-app/GalleryGoogle.odex
sudo rm -rf -v mount/priv-app/GCS
sudo rm -rf -v mount/priv-app/GCS.apk
sudo rm -rf -v mount/priv-app/GCS.odex
sudo rm -rf -v mount/priv-app/GenieWidget
sudo rm -rf -v mount/priv-app/GenieWidget.apk
sudo rm -rf -v mount/priv-app/GenieWidget.odex
sudo rm -rf -v mount/priv-app/Gmail
sudo rm -rf -v mount/priv-app/Gmail.apk
sudo rm -rf -v mount/priv-app/Gmail.odex
sudo rm -rf -v mount/priv-app/Gmail2
sudo rm -rf -v mount/priv-app/Gmail2.apk
sudo rm -rf -v mount/priv-app/Gmail2.odex
sudo rm -rf -v mount/priv-app/GmsCore
sudo rm -rf -v mount/priv-app/GmsCore.apk
sudo rm -rf -v mount/priv-app/GmsCore.odex
sudo rm -rf -v mount/priv-app/GmsCore_update
sudo rm -rf -v mount/priv-app/GmsCore_update.apk
sudo rm -rf -v mount/priv-app/GmsCore_update.odex
sudo rm -rf -v mount/priv-app/GmsCoreSetupPrebuilt
sudo rm -rf -v mount/priv-app/GmsCoreSetupPrebuilt.apk
sudo rm -rf -v mount/priv-app/GmsCoreSetupPrebuilt.odex
sudo rm -rf -v mount/priv-app/GoogleBackupTransport
sudo rm -rf -v mount/priv-app/GoogleBackupTransport.apk
sudo rm -rf -v mount/priv-app/GoogleBackupTransport.odex
sudo rm -rf -v mount/priv-app/GoogleCalendar
sudo rm -rf -v mount/priv-app/GoogleCalendar.apk
sudo rm -rf -v mount/priv-app/GoogleCalendar.odex
sudo rm -rf -v mount/priv-app/GoogleCamera
sudo rm -rf -v mount/priv-app/GoogleCamera.apk
sudo rm -rf -v mount/priv-app/GoogleCamera.odex
sudo rm -rf -v mount/priv-app/GoogleCameraLegacy
sudo rm -rf -v mount/priv-app/GoogleCameraLegacy.apk
sudo rm -rf -v mount/priv-app/GoogleCameraLegacy.odex
sudo rm -rf -v mount/priv-app/GoogleCloudPrint
sudo rm -rf -v mount/priv-app/GoogleCloudPrint.apk
sudo rm -rf -v mount/priv-app/GoogleCloudPrint.odex
sudo rm -rf -v mount/priv-app/GoogleContacts
sudo rm -rf -v mount/priv-app/GoogleContacts.apk
sudo rm -rf -v mount/priv-app/GoogleContacts.odex
sudo rm -rf -v mount/priv-app/GoogleContactsSyncAdapter
sudo rm -rf -v mount/priv-app/GoogleContactsSyncAdapter.apk
sudo rm -rf -v mount/priv-app/GoogleContactsSyncAdapter.odex
sudo rm -rf -v mount/priv-app/GoogleDialer
sudo rm -rf -v mount/priv-app/GoogleDialer.apk
sudo rm -rf -v mount/priv-app/GoogleDialer.odex
sudo rm -rf -v mount/priv-app/GoogleEars
sudo rm -rf -v mount/priv-app/GoogleEars.apk
sudo rm -rf -v mount/priv-app/GoogleEars.odex
sudo rm -rf -v mount/priv-app/GoogleEarth
sudo rm -rf -v mount/priv-app/GoogleEarth.apk
sudo rm -rf -v mount/priv-app/GoogleEarth.odex
sudo rm -rf -v mount/priv-app/GoogleExtServices
sudo rm -rf -v mount/priv-app/GoogleExtServices.apk
sudo rm -rf -v mount/priv-app/GoogleExtServices.odex
sudo rm -rf -v mount/priv-app/GoogleExtShared
sudo rm -rf -v mount/priv-app/GoogleExtShared.apk
sudo rm -rf -v mount/priv-app/GoogleExtShared.odex
sudo rm -rf -v mount/priv-app/GoogleFeedback
sudo rm -rf -v mount/priv-app/GoogleFeedback.apk
sudo rm -rf -v mount/priv-app/GoogleFeedback.odex
sudo rm -rf -v mount/priv-app/GoogleHangouts
sudo rm -rf -v mount/priv-app/GoogleHangouts.apk
sudo rm -rf -v mount/priv-app/GoogleHangouts.odex
sudo rm -rf -v mount/priv-app/GoogleHindiIME
sudo rm -rf -v mount/priv-app/GoogleHindiIME.apk
sudo rm -rf -v mount/priv-app/GoogleHindiIME.odex
sudo rm -rf -v mount/priv-app/GoogleHome
sudo rm -rf -v mount/priv-app/GoogleHome.apk
sudo rm -rf -v mount/priv-app/GoogleHome.odex
sudo rm -rf -v mount/priv-app/GoogleJapaneseInput
sudo rm -rf -v mount/priv-app/GoogleJapaneseInput.apk
sudo rm -rf -v mount/priv-app/GoogleJapaneseInput.odex
sudo rm -rf -v mount/priv-app/GoogleKeep
sudo rm -rf -v mount/priv-app/GoogleKeep.apk
sudo rm -rf -v mount/priv-app/GoogleKeep.odex
sudo rm -rf -v mount/priv-app/GoogleLatinIme
sudo rm -rf -v mount/priv-app/GoogleLatinIme.apk
sudo rm -rf -v mount/priv-app/GoogleLatinIme.odex
sudo rm -rf -v mount/priv-app/GoogleLoginService
sudo rm -rf -v mount/priv-app/GoogleLoginService.apk
sudo rm -rf -v mount/priv-app/GoogleLoginService.odex
sudo rm -rf -v mount/priv-app/GoogleMusic
sudo rm -rf -v mount/priv-app/GoogleMusic.apk
sudo rm -rf -v mount/priv-app/GoogleMusic.odex
sudo rm -rf -v mount/priv-app/GoogleNow
sudo rm -rf -v mount/priv-app/GoogleNow.apk
sudo rm -rf -v mount/priv-app/GoogleNow.odex
sudo rm -rf -v mount/priv-app/GoogleNowVoiceSearch
sudo rm -rf -v mount/priv-app/GoogleNowVoiceSearch.apk
sudo rm -rf -v mount/priv-app/GoogleNowVoiceSearch.odex
sudo rm -rf -v mount/priv-app/GoogleOneTimeInitializer
sudo rm -rf -v mount/priv-app/GoogleOneTimeInitializer.apk
sudo rm -rf -v mount/priv-app/GoogleOneTimeInitializer.odex
sudo rm -rf -v mount/priv-app/GooglePartnerSetup
sudo rm -rf -v mount/priv-app/GooglePartnerSetup.apk
sudo rm -rf -v mount/priv-app/GooglePartnerSetup.odex
sudo rm -rf -v mount/priv-app/GooglePinyinIME
sudo rm -rf -v mount/priv-app/GooglePinyinIME.apk
sudo rm -rf -v mount/priv-app/GooglePinyinIME.odex
sudo rm -rf -v mount/priv-app/GooglePlay
sudo rm -rf -v mount/priv-app/GooglePlay.apk
sudo rm -rf -v mount/priv-app/GooglePlay.odex
sudo rm -rf -v mount/priv-app/GooglePlus
sudo rm -rf -v mount/priv-app/GooglePlus.apk
sudo rm -rf -v mount/priv-app/GooglePlus.odex
sudo rm -rf -v mount/priv-app/GooglePrintRecommendationService
sudo rm -rf -v mount/priv-app/GooglePrintRecommendationService.apk
sudo rm -rf -v mount/priv-app/GooglePrintRecommendationService.odex
sudo rm -rf -v mount/priv-app/GoogleQuickSearchBox
sudo rm -rf -v mount/priv-app/GoogleQuickSearchBox.apk
sudo rm -rf -v mount/priv-app/GoogleQuickSearchBox.odex
sudo rm -rf -v mount/priv-app/GoogleSearch
sudo rm -rf -v mount/priv-app/GoogleSearch.apk
sudo rm -rf -v mount/priv-app/GoogleSearch.odex
sudo rm -rf -v mount/priv-app/GoogleServicesFramework
sudo rm -rf -v mount/priv-app/GoogleServicesFramework.apk
sudo rm -rf -v mount/priv-app/GoogleServicesFramework.odex
sudo rm -rf -v mount/priv-app/GoogleTTS
sudo rm -rf -v mount/priv-app/GoogleTTS.apk
sudo rm -rf -v mount/priv-app/GoogleTTS.odex
sudo rm -rf -v mount/priv-app/GoogleVrCore
sudo rm -rf -v mount/priv-app/GoogleVrCore.apk
sudo rm -rf -v mount/priv-app/GoogleVrCore.odex
sudo rm -rf -v mount/priv-app/GoogleZhuyinIME
sudo rm -rf -v mount/priv-app/GoogleZhuyinIME.apk
sudo rm -rf -v mount/priv-app/GoogleZhuyinIME.odex
sudo rm -rf -v mount/priv-app/Hangouts
sudo rm -rf -v mount/priv-app/Hangouts.apk
sudo rm -rf -v mount/priv-app/Hangouts.odex
sudo rm -rf -v mount/priv-app/HangoutsDialer
sudo rm -rf -v mount/priv-app/HangoutsDialer.apk
sudo rm -rf -v mount/priv-app/HangoutsDialer.odex
sudo rm -rf -v mount/priv-app/HelpRtcPrebuilt
sudo rm -rf -v mount/priv-app/HelpRtcPrebuilt.apk
sudo rm -rf -v mount/priv-app/HelpRtcPrebuilt.odex
sudo rm -rf -v mount/priv-app/HotwordEnrollment
sudo rm -rf -v mount/priv-app/HotwordEnrollment.apk
sudo rm -rf -v mount/priv-app/HotwordEnrollment.odex
sudo rm -rf -v mount/priv-app/HotwordEnrollmentOKGoogleWCD9340
sudo rm -rf -v mount/priv-app/HotwordEnrollmentOKGoogleWCD9340.apk
sudo rm -rf -v mount/priv-app/HotwordEnrollmentOKGoogleWCD9340.odex
sudo rm -rf -v mount/priv-app/HotwordEnrollmentXGoogleWCD9340
sudo rm -rf -v mount/priv-app/HotwordEnrollmentXGoogleWCD9340.apk
sudo rm -rf -v mount/priv-app/HotwordEnrollmentXGoogleWCD9340.odex
sudo rm -rf -v mount/priv-app/iWnnIME
sudo rm -rf -v mount/priv-app/iWnnIME.apk
sudo rm -rf -v mount/priv-app/iWnnIME.odex
sudo rm -rf -v mount/priv-app/iWnnIME_Kbd_White
sudo rm -rf -v mount/priv-app/iWnnIME_Kbd_White.apk
sudo rm -rf -v mount/priv-app/iWnnIME_Kbd_White.odex
sudo rm -rf -v mount/priv-app/Keep
sudo rm -rf -v mount/priv-app/Keep.apk
sudo rm -rf -v mount/priv-app/Keep.odex
sudo rm -rf -v mount/priv-app/KoreanIME
sudo rm -rf -v mount/priv-app/KoreanIME.apk
sudo rm -rf -v mount/priv-app/KoreanIME.odex
sudo rm -rf -v mount/priv-app/LatinIME
sudo rm -rf -v mount/priv-app/LatinIME.apk
sudo rm -rf -v mount/priv-app/LatinIME.odex
sudo rm -rf -v mount/priv-app/LatinImeDictionaryPack
sudo rm -rf -v mount/priv-app/LatinImeDictionaryPack.apk
sudo rm -rf -v mount/priv-app/LatinImeDictionaryPack.odex
sudo rm -rf -v mount/priv-app/LatinImeGoogle
sudo rm -rf -v mount/priv-app/LatinImeGoogle.apk
sudo rm -rf -v mount/priv-app/LatinImeGoogle.odex
sudo rm -rf -v mount/priv-app/LatinIMEGooglePrebuilt
sudo rm -rf -v mount/priv-app/LatinIMEGooglePrebuilt.apk
sudo rm -rf -v mount/priv-app/LatinIMEGooglePrebuilt.odex
sudo rm -rf -v mount/priv-app/LatinImeTutorial
sudo rm -rf -v mount/priv-app/LatinImeTutorial.apk
sudo rm -rf -v mount/priv-app/LatinImeTutorial.odex
sudo rm -rf -v mount/priv-app/Magazines
sudo rm -rf -v mount/priv-app/Magazines.apk
sudo rm -rf -v mount/priv-app/Magazines.odex
sudo rm -rf -v mount/priv-app/Maps
sudo rm -rf -v mount/priv-app/Maps.apk
sudo rm -rf -v mount/priv-app/Maps.odex
sudo rm -rf -v mount/priv-app/MarketUpdater
sudo rm -rf -v mount/priv-app/MarketUpdater.apk
sudo rm -rf -v mount/priv-app/MarketUpdater.odex
sudo rm -rf -v mount/priv-app/MediaUploader
sudo rm -rf -v mount/priv-app/MediaUploader.apk
sudo rm -rf -v mount/priv-app/MediaUploader.odex
sudo rm -rf -v mount/priv-app/Music2
sudo rm -rf -v mount/priv-app/Music2.apk
sudo rm -rf -v mount/priv-app/Music2.odex
sudo rm -rf -v mount/priv-app/NetworkLocation
sudo rm -rf -v mount/priv-app/NetworkLocation.apk
sudo rm -rf -v mount/priv-app/NetworkLocation.odex
sudo rm -rf -v mount/priv-app/Newsstand
sudo rm -rf -v mount/priv-app/Newsstand.apk
sudo rm -rf -v mount/priv-app/Newsstand.odex
sudo rm -rf -v mount/priv-app/NewsstandStub
sudo rm -rf -v mount/priv-app/NewsstandStub.apk
sudo rm -rf -v mount/priv-app/NewsstandStub.odex
sudo rm -rf -v mount/priv-app/NewsWeather
sudo rm -rf -v mount/priv-app/NewsWeather.apk
sudo rm -rf -v mount/priv-app/NewsWeather.odex
sudo rm -rf -v mount/priv-app/NexusLauncherIcons
sudo rm -rf -v mount/priv-app/NexusLauncherIcons.apk
sudo rm -rf -v mount/priv-app/NexusLauncherIcons.odex
sudo rm -rf -v mount/priv-app/NexusLauncherPrebuilt
sudo rm -rf -v mount/priv-app/NexusLauncherPrebuilt.apk
sudo rm -rf -v mount/priv-app/NexusLauncherPrebuilt.odex
sudo rm -rf -v mount/priv-app/NexusWallpapersStubPrebuilt2017
sudo rm -rf -v mount/priv-app/NexusWallpapersStubPrebuilt2017.apk
sudo rm -rf -v mount/priv-app/NexusWallpapersStubPrebuilt2017.odex
sudo rm -rf -v mount/priv-app/OccamQuickOffice
sudo rm -rf -v mount/priv-app/OccamQuickOffice.apk
sudo rm -rf -v mount/priv-app/OccamQuickOffice.odex
sudo rm -rf -v mount/priv-app/OneTimeInitializer
sudo rm -rf -v mount/priv-app/OneTimeInitializer.apk
sudo rm -rf -v mount/priv-app/OneTimeInitializer.odex
sudo rm -rf -v mount/priv-app/PartnerBookmarksProvider
sudo rm -rf -v mount/priv-app/PartnerBookmarksProvider.apk
sudo rm -rf -v mount/priv-app/PartnerBookmarksProvider.odex
sudo rm -rf -v mount/priv-app/Phonesky
sudo rm -rf -v mount/priv-app/Phonesky.apk
sudo rm -rf -v mount/priv-app/Phonesky.odex
sudo rm -rf -v mount/priv-app/Photos
sudo rm -rf -v mount/priv-app/Photos.apk
sudo rm -rf -v mount/priv-app/Photos.odex
sudo rm -rf -v mount/priv-app/PlayAutoInstallConfig
sudo rm -rf -v mount/priv-app/PlayAutoInstallConfig.apk
sudo rm -rf -v mount/priv-app/PlayAutoInstallConfig.odex
sudo rm -rf -v mount/priv-app/PlayGames
sudo rm -rf -v mount/priv-app/PlayGames.apk
sudo rm -rf -v mount/priv-app/PlayGames.odex
sudo rm -rf -v mount/priv-app/PlayStore
sudo rm -rf -v mount/priv-app/PlayStore.apk
sudo rm -rf -v mount/priv-app/PlayStore.odex
sudo rm -rf -v mount/priv-app/PlusOne
sudo rm -rf -v mount/priv-app/PlusOne.apk
sudo rm -rf -v mount/priv-app/PlusOne.odex
sudo rm -rf -v mount/priv-app/PrebuiltBugle
sudo rm -rf -v mount/priv-app/PrebuiltBugle.apk
sudo rm -rf -v mount/priv-app/PrebuiltBugle.odex
sudo rm -rf -v mount/priv-app/PrebuiltBugleStub
sudo rm -rf -v mount/priv-app/PrebuiltBugleStub.apk
sudo rm -rf -v mount/priv-app/PrebuiltBugleStub.odex
sudo rm -rf -v mount/priv-app/PrebuiltDeskClockGoogle
sudo rm -rf -v mount/priv-app/PrebuiltDeskClockGoogle.apk
sudo rm -rf -v mount/priv-app/PrebuiltDeskClockGoogle.odex
sudo rm -rf -v mount/priv-app/PrebuiltEmailGoogle
sudo rm -rf -v mount/priv-app/PrebuiltEmailGoogle.apk
sudo rm -rf -v mount/priv-app/PrebuiltEmailGoogle.odex
sudo rm -rf -v mount/priv-app/PrebuiltExchange3Google
sudo rm -rf -v mount/priv-app/PrebuiltExchange3Google.apk
sudo rm -rf -v mount/priv-app/PrebuiltExchange3Google.odex
sudo rm -rf -v mount/priv-app/PrebuiltGmail
sudo rm -rf -v mount/priv-app/PrebuiltGmail.apk
sudo rm -rf -v mount/priv-app/PrebuiltGmail.odex
sudo rm -rf -v mount/priv-app/PrebuiltGmsCore
sudo rm -rf -v mount/priv-app/PrebuiltGmsCore.apk
sudo rm -rf -v mount/priv-app/PrebuiltGmsCore.odex
sudo rm -rf -v mount/priv-app/PrebuiltGmsCorePix
sudo rm -rf -v mount/priv-app/PrebuiltGmsCorePix.apk
sudo rm -rf -v mount/priv-app/PrebuiltGmsCorePix.odex
sudo rm -rf -v mount/priv-app/PrebuiltKeep
sudo rm -rf -v mount/priv-app/PrebuiltKeep.apk
sudo rm -rf -v mount/priv-app/PrebuiltKeep.odex
sudo rm -rf -v mount/priv-app/PrebuiltKeepStub
sudo rm -rf -v mount/priv-app/PrebuiltKeepStub.apk
sudo rm -rf -v mount/priv-app/PrebuiltKeepStub.odex
sudo rm -rf -v mount/priv-app/PrebuiltNewsWeather
sudo rm -rf -v mount/priv-app/PrebuiltNewsWeather.apk
sudo rm -rf -v mount/priv-app/PrebuiltNewsWeather.odex
sudo rm -rf -v mount/priv-app/PrintSpooler
sudo rm -rf -v mount/priv-app/PrintSpooler.apk
sudo rm -rf -v mount/priv-app/PrintSpooler.odex
sudo rm -rf -v mount/priv-app/QuickOffice
sudo rm -rf -v mount/priv-app/QuickOffice.apk
sudo rm -rf -v mount/priv-app/QuickOffice.odex
sudo rm -rf -v mount/priv-app/QuickSearchBox
sudo rm -rf -v mount/priv-app/QuickSearchBox.apk
sudo rm -rf -v mount/priv-app/QuickSearchBox.odex
sudo rm -rf -v mount/priv-app/SettingsGoogle
sudo rm -rf -v mount/priv-app/SettingsGoogle.apk
sudo rm -rf -v mount/priv-app/SettingsGoogle.odex
sudo rm -rf -v mount/priv-app/SetupWizard
sudo rm -rf -v mount/priv-app/SetupWizard.apk
sudo rm -rf -v mount/priv-app/SetupWizard.odex
sudo rm -rf -v mount/priv-app/StorageManagerGoogle
sudo rm -rf -v mount/priv-app/StorageManagerGoogle.apk
sudo rm -rf -v mount/priv-app/StorageManagerGoogle.odex
sudo rm -rf -v mount/priv-app/Street
sudo rm -rf -v mount/priv-app/Street.apk
sudo rm -rf -v mount/priv-app/Street.odex
sudo rm -rf -v mount/priv-app/SystemUIGoogle
sudo rm -rf -v mount/priv-app/SystemUIGoogle.apk
sudo rm -rf -v mount/priv-app/SystemUIGoogle.odex
sudo rm -rf -v mount/priv-app/TagGoogle
sudo rm -rf -v mount/priv-app/TagGoogle.apk
sudo rm -rf -v mount/priv-app/TagGoogle.odex
sudo rm -rf -v mount/priv-app/Talk
sudo rm -rf -v mount/priv-app/Talk.apk
sudo rm -rf -v mount/priv-app/Talk.odex
sudo rm -rf -v mount/priv-app/talkback
sudo rm -rf -v mount/priv-app/talkback.apk
sudo rm -rf -v mount/priv-app/talkback.odex
sudo rm -rf -v mount/priv-app/TranslatePrebuilt
sudo rm -rf -v mount/priv-app/TranslatePrebuilt.apk
sudo rm -rf -v mount/priv-app/TranslatePrebuilt.odex
sudo rm -rf -v mount/priv-app/Turbo
sudo rm -rf -v mount/priv-app/Turbo.apk
sudo rm -rf -v mount/priv-app/Turbo.odex
sudo rm -rf -v mount/priv-app/Tycho
sudo rm -rf -v mount/priv-app/Tycho.apk
sudo rm -rf -v mount/priv-app/Tycho.odex
sudo rm -rf -v mount/priv-app/Velvet
sudo rm -rf -v mount/priv-app/Velvet.apk
sudo rm -rf -v mount/priv-app/Velvet.odex
sudo rm -rf -v mount/priv-app/Velvet_update
sudo rm -rf -v mount/priv-app/Velvet_update.apk
sudo rm -rf -v mount/priv-app/Velvet_update.odex
sudo rm -rf -v mount/priv-app/Vending
sudo rm -rf -v mount/priv-app/Vending.apk
sudo rm -rf -v mount/priv-app/Vending.odex
sudo rm -rf -v mount/priv-app/Videos
sudo rm -rf -v mount/priv-app/Videos.apk
sudo rm -rf -v mount/priv-app/Videos.odex
sudo rm -rf -v mount/priv-app/VoiceSearch
sudo rm -rf -v mount/priv-app/VoiceSearch.apk
sudo rm -rf -v mount/priv-app/VoiceSearch.odex
sudo rm -rf -v mount/priv-app/VoiceSearchStub
sudo rm -rf -v mount/priv-app/VoiceSearchStub.apk
sudo rm -rf -v mount/priv-app/VoiceSearchStub.odex
sudo rm -rf -v mount/priv-app/Wallet
sudo rm -rf -v mount/priv-app/Wallet.apk
sudo rm -rf -v mount/priv-app/Wallet.odex
sudo rm -rf -v mount/priv-app/WallpaperPickerGooglePrebuilt
sudo rm -rf -v mount/priv-app/WallpaperPickerGooglePrebuilt.apk
sudo rm -rf -v mount/priv-app/WallpaperPickerGooglePrebuilt.odex
sudo rm -rf -v mount/priv-app/WallpapersBReel2017
sudo rm -rf -v mount/priv-app/WallpapersBReel2017.apk
sudo rm -rf -v mount/priv-app/WallpapersBReel2017.odex
sudo rm -rf -v mount/priv-app/YouTube
sudo rm -rf -v mount/priv-app/YouTube.apk
sudo rm -rf -v mount/priv-app/YouTube.odex
sudo rm -rf -v mount/tts
sudo rm -rf -v mount/usr/srec
sudo rm -rf -v mount/vendor/lib/libfrsdk.so
sudo rm -rf -v mount/vendor/lib64/libfrsdk.so
sudo rm -rf -v mount/vendor/pittpatt
echo ""

# Building zip
mkdir -p out/zip/META-INF/com/google/android/
mkdir out/zip/system/

# Copy apk's and other stuff
echo "copying files..."
cp -R -v system/* out/zip/system/
echo ""

cp -r vs986/boot.img out/zip/
cp -r vs986/zip/* out/zip/META-INF/com/google/android/
sudo cp -r -v vs986/build.prop mount/


# Print build date to build.prop
echo ""
echo "printing the build date to build.prop"
echo "" | sudo tee -a mount/build.prop
echo "#" | sudo tee -a mount/build.prop
echo "# autogenerated by build.sh" | sudo tee -a mount/build.prop
echo "#" | sudo tee -a mount/build.prop
echo "" | sudo tee -a mount/build.prop
echo "ro.lge.swversion=VS986 2BA revamped $fireDate" | sudo tee -a mount/build.prop
echo "ro.lge.swversion_short=2BA revamped  $fireDate" | sudo tee -a mount/build.prop
if [ "${build}" = "dev" ];
then
    echo ""
    echo "# adb debuging " | sudo tee -a mount/build.prop
    echo "sys.usb.state=auto_conf,adb" | sudo tee -a mount/build.prop
    echo "persist.service.adb.enable=1" | sudo tee -a mount/build.prop
    echo "persist.service.debuggable=1" | sudo tee -a mount/build.prop
fi

# Unmount system.img
sudo umount mount/

# Zipping up rom
cp -r out/system.img out/zip/
cd out/zip/
echo "Zipping up..."
zip -r 2BA_rev_$fileDate *
cd ..
cp -r zip/2BA_rev_$fileDate.zip ../
echo "done"
echo "zip name: 2BA_rev_$fileDate.zip"
echo "The zip is in the root dir"

